name: sast-self-hosted

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SAST:
    runs-on: self-hosted
    container:
      image: registry.gitlab.com/whoissqr/sig-docker-reg:latest
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
          go-version: 1.15

    - name: Build
      run: cov-build --dir idir go build -v ./...
      
    - name: Analyze
      run: cov-analyze --dir idir --ticker-mode none --strip-path $GITHUB_WORKSPACE --all --webapp-security --enable-audit-mode

    - name: Export
      run: cov-format-errors --dir idir --json-output-v8 govwa.json; \
            --/opt/coverity/analysis/2021.03/node/bin/node cov-format-sarif-for-github.js \
            --inputFile  govwa.json \
            --outputFile govwaSARIF.json \
            --githubUrl https://github.com \
            --repoName whoissqr/govwa
      
    - name: Test
      run: go test -v ./...
