name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      container: coverity:coverity
      runs-on: coverity:coverity
      steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.15

      - name: Build
        run: cov-build --dir idir go build -v ./...

      - name: Test
        run: go test -v ./...
