name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_job:
    runs-on: self-hosted
    container:
      image: registry.gitlab.com/whoissqr/sig-docker-reg:latest
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
          go-version: 1.15

    - name: Build
      run: cov-build --dir idir go build -v ./...

    - name: Test
      run: go test -v ./...
